# Deployment workflow for Azure App Service - Optimized for minimal file count
name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Create production deployment
      run: |
        echo "Creating production deployment with all required dependencies..."
        
        # Create minimal deploy directory
        mkdir deploy
        
        # Copy only essential application files
        cp package.json deploy/
        cp index.js deploy/
        cp bot.js deploy/
        cp config.js deploy/
        cp database.js deploy/
        cp scheduler.js deploy/
        cp locationAliases.js deploy/
        cp web.config deploy/
        
        # Copy essential directories
        cp -r utils deploy/ 2>/dev/null || true
        cp -r cards deploy/ 2>/dev/null || true
        cp -r data deploy/ 2>/dev/null || true
        cp -r teams-package deploy/ 2>/dev/null || true
        
        # Create deployment configuration
        echo "[config]" > deploy/.deployment
        echo "project = ." >> deploy/.deployment
        
        echo "Application files copied. Current file count:"
        find deploy -type f | wc -l
    
    - name: Install production dependencies with aggressive cleanup
      run: |
        cd deploy
        echo "Installing production dependencies..."
        
        # Install production dependencies normally to ensure all sub-dependencies are included
        npm install --production --silent --no-audit --no-fund --no-optional
        
        echo "Dependencies installed. Starting aggressive cleanup..."
        
        # Phase 1: Remove documentation and metadata files
        find node_modules -name "*.md" -type f -delete 2>/dev/null || true
        find node_modules -name "*.txt" -type f -delete 2>/dev/null || true
        find node_modules -name "README*" -type f -delete 2>/dev/null || true
        find node_modules -name "CHANGELOG*" -type f -delete 2>/dev/null || true
        find node_modules -name "LICENSE*" -type f -delete 2>/dev/null || true
        find node_modules -name "NOTICE*" -type f -delete 2>/dev/null || true
        find node_modules -name "HISTORY*" -type f -delete 2>/dev/null || true
        find node_modules -name "AUTHORS*" -type f -delete 2>/dev/null || true
        find node_modules -name "CONTRIBUTORS*" -type f -delete 2>/dev/null || true
        
        # Phase 2: Remove test and development files
        rm -rf node_modules/*/test 2>/dev/null || true
        rm -rf node_modules/*/tests 2>/dev/null || true
        rm -rf node_modules/*/__tests__ 2>/dev/null || true
        rm -rf node_modules/*/spec 2>/dev/null || true
        rm -rf node_modules/*/docs 2>/dev/null || true
        rm -rf node_modules/*/documentation 2>/dev/null || true
        rm -rf node_modules/*/.github 2>/dev/null || true
        rm -rf node_modules/*/examples 2>/dev/null || true
        rm -rf node_modules/*/example 2>/dev/null || true
        rm -rf node_modules/*/samples 2>/dev/null || true
        rm -rf node_modules/*/sample 2>/dev/null || true
        rm -rf node_modules/*/benchmark 2>/dev/null || true
        rm -rf node_modules/*/benchmarks 2>/dev/null || true
        
        # Phase 3: Remove build and config files
        find node_modules -name "*.test.js" -type f -delete 2>/dev/null || true
        find node_modules -name "*.spec.js" -type f -delete 2>/dev/null || true
        find node_modules -name "*test*.js" -type f -delete 2>/dev/null || true
        find node_modules -name "tsconfig*.json" -type f -delete 2>/dev/null || true
        find node_modules -name "jest.config.*" -type f -delete 2>/dev/null || true
        find node_modules -name "babel.config.*" -type f -delete 2>/dev/null || true
        find node_modules -name "webpack.config.*" -type f -delete 2>/dev/null || true
        find node_modules -name ".eslintrc*" -type f -delete 2>/dev/null || true
        find node_modules -name ".prettierrc*" -type f -delete 2>/dev/null || true
        find node_modules -name ".gitignore" -type f -delete 2>/dev/null || true
        find node_modules -name ".npmignore" -type f -delete 2>/dev/null || true
        
        # Phase 4: Remove TypeScript and source maps (keep runtime JS)
        find node_modules -name "*.d.ts" -type f -delete 2>/dev/null || true
        find node_modules -name "*.d.ts.map" -type f -delete 2>/dev/null || true
        find node_modules -name "*.js.map" -type f -delete 2>/dev/null || true
        find node_modules -name "*.map" -type f -delete 2>/dev/null || true
        
        # Phase 5: Remove cache and coverage directories
        rm -rf node_modules/*/.nyc_output 2>/dev/null || true
        rm -rf node_modules/*/coverage 2>/dev/null || true
        rm -rf node_modules/*/.coverage 2>/dev/null || true
        rm -rf node_modules/*/.cache 2>/dev/null || true
        rm -rf node_modules/*/cache 2>/dev/null || true
        
        # Phase 6: Remove editor files
        find node_modules -name "*.swp" -type f -delete 2>/dev/null || true
        find node_modules -name "*.swo" -type f -delete 2>/dev/null || true
        find node_modules -name "*~" -type f -delete 2>/dev/null || true
        rm -rf node_modules/*/.vscode 2>/dev/null || true
        rm -rf node_modules/*/.idea 2>/dev/null || true
        
        # Phase 7: Remove empty directories
        find node_modules -type d -empty -delete 2>/dev/null || true
        
        cd ..
        echo "After aggressive cleanup (keeping all runtime dependencies):"
        find deploy -type f | wc -l
        echo "Deploy directory size:"
        du -sh deploy/
    
    - name: Final cleanup and create deployment package
      run: |
        cd deploy
        
        echo "Performing final cleanup..."
        
        # Remove any remaining unnecessary files
        find . -name ".DS_Store" -type f -delete 2>/dev/null || true
        find . -name "Thumbs.db" -type f -delete 2>/dev/null || true
        find . -name "*.log" -type f -delete 2>/dev/null || true
        
        # Remove empty directories
        find . -type d -empty -delete 2>/dev/null || true
        
        echo "FINAL file count after cleanup:"
        find . -type f | wc -l
        
        echo "Creating deployment ZIP..."
        zip -r ../deployment.zip . --quiet
        
        cd ..
        
        echo "Final deployment package info:"
        ls -lh deployment.zip
        echo "Files in deployment ZIP:"
        unzip -l deployment.zip | tail -1
        
        echo "Deployment optimization complete!"
        echo "All runtime dependencies included with aggressive cleanup"
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Prepare for deployment
      run: |
        echo "Preparing Azure App Service for deployment..."
        
        # Stop the app service to prevent deployment conflicts
        echo "Stopping app service to allow deployment..."
        az webapp stop --resource-group rg-location-bot --name location-bot-app-v2
        
        # Wait a moment for the stop to take effect
        sleep 10
        
        echo "App service stopped, ready for deployment"
    
    - name: Deploy to Azure App Service
      run: |
        echo "Deploying production package to Azure App Service..."
        az webapp deployment source config-zip \
          --resource-group rg-location-bot \
          --name location-bot-app-v2 \
          --src deployment.zip
        
        echo "Deployment completed successfully!"
    
    - name: Start app service and verify deployment
      run: |
        echo "Starting app service after deployment..."
        az webapp start --resource-group rg-location-bot --name location-bot-app-v2
        
        # Wait for app to start
        sleep 15
        
        # Show deployment status
        echo "Checking app service status..."
        az webapp show \
          --resource-group rg-location-bot \
          --name location-bot-app-v2 \
          --query "state" \
          --output tsv
        
        echo "Deployment and restart completed!" 