name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install production dependencies only
      run: |
        # Clean install with production only
        npm ci --omit=dev --silent
        
        # Remove unnecessary files from node_modules
        find node_modules -name "*.md" -type f -delete 2>/dev/null || true
        find node_modules -name "*.txt" -type f -delete 2>/dev/null || true
        find node_modules -name "*.yml" -type f -delete 2>/dev/null || true
        find node_modules -name "*.yaml" -type f -delete 2>/dev/null || true
        find node_modules -name "CHANGELOG*" -type f -delete 2>/dev/null || true
        find node_modules -name "LICENSE*" -type f -delete 2>/dev/null || true
        find node_modules -name "NOTICE*" -type f -delete 2>/dev/null || true
        rm -rf node_modules/.cache 2>/dev/null || true
        rm -rf node_modules/*/test 2>/dev/null || true
        rm -rf node_modules/*/tests 2>/dev/null || true
        rm -rf node_modules/*/docs 2>/dev/null || true
        rm -rf node_modules/*/.github 2>/dev/null || true
        rm -rf node_modules/*/examples 2>/dev/null || true
        rm -rf node_modules/*/benchmark 2>/dev/null || true
        rm -rf node_modules/*/*.md 2>/dev/null || true
        
        # Show optimized node_modules size
        echo "Optimized node_modules size:"
        du -sh node_modules/
        echo "Optimized node_modules file count:"
        find node_modules -type f | wc -l
    
    - name: Create optimized deployment artifact
      run: |
        echo "Creating deployment directory..."
        mkdir deploy
        
        # Copy essential application files (check if they exist first)
        [ -f package.json ] && cp package.json deploy/ || echo "package.json not found"
        [ -f index.js ] && cp index.js deploy/ || echo "index.js not found"
        [ -f bot.js ] && cp bot.js deploy/ || echo "bot.js not found"
        [ -f config.js ] && cp config.js deploy/ || echo "config.js not found"
        [ -f database.js ] && cp database.js deploy/ || echo "database.js not found"
        [ -f scheduler.js ] && cp scheduler.js deploy/ || echo "scheduler.js not found"
        [ -f locationAliases.js ] && cp locationAliases.js deploy/ || echo "locationAliases.js not found"
        [ -f web.config ] && cp web.config deploy/ || echo "web.config not found"
        
        # Copy deployment configuration files if they exist
        [ -f .deployment ] && cp .deployment deploy/ || echo ".deployment not found - creating basic one"
        if [ ! -f deploy/.deployment ]; then
          echo "[config]" > deploy/.deployment
          echo "project = ." >> deploy/.deployment
        fi
        
        # Copy essential directories if they exist
        [ -d utils ] && cp -r utils deploy/ || echo "utils directory not found"
        [ -d cards ] && cp -r cards deploy/ || echo "cards directory not found"
        [ -d data ] && cp -r data deploy/ || echo "data directory not found"
        [ -d teams-package ] && cp -r teams-package deploy/ || echo "teams-package directory not found"
        
        # Copy optimized node_modules
        [ -d node_modules ] && cp -r node_modules deploy/ || echo "node_modules not found"
        
        # Show deployment contents
        echo "Deployment package file count before ZIP:"
        find deploy -type f | wc -l
        echo "Deployment size before ZIP:"
        du -sh deploy/
    
    - name: Create highly optimized deployment package
      run: |
        # Additional aggressive cleanup of deploy directory before ZIP
        echo "Performing aggressive cleanup before ZIP creation..."
        
        # Remove all documentation and metadata files from deploy directory
        find deploy -name "*.md" -type f -delete 2>/dev/null || true
        find deploy -name "*.txt" -type f -delete 2>/dev/null || true
        find deploy -name "*.yml" -type f -delete 2>/dev/null || true
        find deploy -name "*.yaml" -type f -delete 2>/dev/null || true
        find deploy -name "CHANGELOG*" -type f -delete 2>/dev/null || true
        find deploy -name "LICENSE*" -type f -delete 2>/dev/null || true
        find deploy -name "NOTICE*" -type f -delete 2>/dev/null || true
        find deploy -name "README*" -type f -delete 2>/dev/null || true
        find deploy -name ".gitignore" -type f -delete 2>/dev/null || true
        find deploy -name ".gitattributes" -type f -delete 2>/dev/null || true
        find deploy -name ".npmignore" -type f -delete 2>/dev/null || true
        find deploy -name ".eslintrc*" -type f -delete 2>/dev/null || true
        find deploy -name ".prettierrc*" -type f -delete 2>/dev/null || true
        find deploy -name "*.test.js" -type f -delete 2>/dev/null || true
        find deploy -name "*.spec.js" -type f -delete 2>/dev/null || true
        find deploy -name "tsconfig*.json" -type f -delete 2>/dev/null || true
        find deploy -name "jest.config.*" -type f -delete 2>/dev/null || true
        find deploy -name "babel.config.*" -type f -delete 2>/dev/null || true
        find deploy -name "webpack.config.*" -type f -delete 2>/dev/null || true
        
        # Remove empty directories
        find deploy -type d -empty -delete 2>/dev/null || true
        
        echo "Final file count after aggressive cleanup:"
        find deploy -type f | wc -l
        
        cd deploy
        echo "Creating optimized deployment zip with aggressive exclusions..."
        
        # Create ZIP with just the essential files
        zip -r ../deployment.zip . \
          --quiet \
          -x "*.DS_Store*" \
          -x "*/.DS_Store*" \
          -x "*/.*" \
          -x "*~"
        
        cd ..
        echo "Final deployment package info:"
        ls -lh deployment.zip
        
        # Extract and count files in the ZIP to verify optimization
        echo "Files actually included in deployment ZIP:"
        unzip -l deployment.zip | wc -l
        echo "Deployment package optimization complete!"
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to Azure App Service
      run: |
        echo "Deploying optimized package to Azure App Service..."
        az webapp deployment source config-zip \
          --resource-group rg-location-bot \
          --name location-bot-app \
          --src deployment.zip
        
        echo "Deployment completed successfully!"
        
        # Show deployment status
        az webapp show \
          --resource-group rg-location-bot \
          --name location-bot-app \
          --query "state" \
          --output tsv 