name: Deploy to Azure

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci --production

    - name: Create deployment package
      run: |
        echo "Creating deployment package..."
        
        # Create a clean package without unnecessary files
        mkdir -p deploy-package
        
        # Copy essential application files
        cp package.json deploy-package/
        cp package-lock.json deploy-package/
        cp index.js deploy-package/
        cp simple-test.js deploy-package/
        cp config.js deploy-package/
        cp -r bot.js deploy-package/ 2>/dev/null || echo "bot.js not found, skipping"
        cp -r scheduler.js deploy-package/ 2>/dev/null || echo "scheduler.js not found, skipping"
        cp -r database.js deploy-package/ 2>/dev/null || echo "database.js not found, skipping"
        cp -r utils deploy-package/ 2>/dev/null || echo "utils directory not found, skipping"
        cp -r dialogs deploy-package/ 2>/dev/null || echo "dialogs directory not found, skipping"
        cp -r node_modules deploy-package/
        
        # Create .deployment file
        echo "[config]" > deploy-package/.deployment
        echo "SCM_DO_BUILD_DURING_DEPLOYMENT=false" >> deploy-package/.deployment
        
        echo "Package contents:"
        ls -la deploy-package/
        
        echo "Total files in package:"
        find deploy-package -type f | wc -l

    - name: Azure CLI Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure App Service
      run: |
        echo "Stopping app service..."
        az webapp stop --name location-bot-app --resource-group rg-location-bot
        
        echo "Creating deployment zip..."
        cd deploy-package
        zip -r ../app-deploy.zip . -x "*.git*" "*.DS_Store"
        cd ..
        
        echo "Deploying via Azure CLI..."
        az webapp deployment source config-zip \
          --resource-group rg-location-bot \
          --name location-bot-app \
          --src app-deploy.zip
        
        echo "Setting startup command..."
        az webapp config set \
          --name location-bot-app \
          --resource-group rg-location-bot \
          --startup-file "node simple-test.js"
        
        echo "Starting app service..."
        az webapp start --name location-bot-app --resource-group rg-location-bot
        
        echo "Waiting for startup..."
        sleep 30

    - name: Verify deployment
      run: |
        echo "Checking app status..."
        az webapp show --name location-bot-app --resource-group rg-location-bot --query "state" -o tsv
        
        echo "Testing app endpoint..."
        curl -f https://location-bot-app.azurewebsites.net/ || echo "App not responding yet, but deployment completed" 