name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci --production --silent
    
    - name: Create deployment package
      run: |
        # Create deployment package directory
        mkdir -p ../deployment-package
        
        # Copy files using rsync to exclude unnecessary items
        rsync -av --exclude='node_modules/.cache' \
                  --exclude='.git' \
                  --exclude='.github' \
                  --exclude='tests' \
                  --exclude='test' \
                  --exclude='__tests__' \
                  --exclude='*.test.js' \
                  --exclude='*.spec.js' \
                  --exclude='*.md' \
                  --exclude='docs/' \
                  --exclude='.gitignore' \
                  --exclude='jest.config.js' \
                  --exclude='nodemon.json' \
                  --exclude='.vscode' \
                  --exclude='.idea' \
                  --exclude='coverage' \
                  --exclude='logs' \
                  --exclude='*.log' \
                  --exclude='.DS_Store' \
                  --exclude='deployment-package' \
                  ./ ../deployment-package/
        
        # Move to deployment package directory
        cd ../deployment-package
        
        # Optimize package.json for production
        node -e "
          const pkg = require('./package.json');
          delete pkg.devDependencies;
          delete pkg.scripts.dev;
          delete pkg.scripts.test;
          delete pkg.scripts['test:watch'];
          delete pkg.scripts['test:coverage'];
          delete pkg.scripts.lint;
          delete pkg.scripts['lint:fix'];
          require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));
        "
        
        # Clean up any remaining dev files
        find . -name "*.test.js" -delete 2>/dev/null || true
        find . -name "*.spec.js" -delete 2>/dev/null || true
        rm -rf node_modules/.cache 2>/dev/null || true
        
        # List contents for debugging
        echo "Deployment package contents:"
        ls -la
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_APP_NAME }}
        package: ../deployment-package 