name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install production dependencies only
      run: |
        # Clean install with production only
        npm ci --omit=dev --silent
        
        # Remove unnecessary files from node_modules
        find node_modules -name "*.md" -type f -delete 2>/dev/null || true
        find node_modules -name "*.txt" -type f -delete 2>/dev/null || true
        find node_modules -name "*.yml" -type f -delete 2>/dev/null || true
        find node_modules -name "*.yaml" -type f -delete 2>/dev/null || true
        find node_modules -name "CHANGELOG*" -type f -delete 2>/dev/null || true
        find node_modules -name "LICENSE*" -type f -delete 2>/dev/null || true
        find node_modules -name "NOTICE*" -type f -delete 2>/dev/null || true
        rm -rf node_modules/.cache 2>/dev/null || true
        rm -rf node_modules/*/test 2>/dev/null || true
        rm -rf node_modules/*/tests 2>/dev/null || true
        rm -rf node_modules/*/docs 2>/dev/null || true
        rm -rf node_modules/*/.github 2>/dev/null || true
    
    - name: Create optimized deployment artifact
      run: |
        echo "Creating deployment directory..."
        mkdir deploy
        
        # Copy only essential application files
        cp package.json deploy/
        cp index.js deploy/
        cp bot.js deploy/
        cp config.js deploy/
        cp database.js deploy/
        cp scheduler.js deploy/
        cp locationAliases.js deploy/
        cp web.config deploy/
        cp .deployment deploy/
        
        # Copy essential directories
        cp -r utils deploy/ 2>/dev/null || true
        cp -r cards deploy/ 2>/dev/null || true
        cp -r data deploy/ 2>/dev/null || true
        cp -r teams-package deploy/ 2>/dev/null || true
        
        # Copy optimized node_modules
        cp -r node_modules deploy/
        
        # Show deployment size
        echo "Deployment package contents:"
        du -sh deploy/
        echo "File count:"
        find deploy -type f | wc -l
    
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'location-bot-app'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './deploy' 